<!DOCTYPE html>
<html lang="zh_CN" style="overflow: hidden;">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- Set render engine for 360 browser -->
  <meta name="renderer" content="webkit">
  <!--  模板借鉴自ThinkCMF-->
  <title>PhalconCMS 后台管理系统</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- HTML5 shim for IE8 support of HTML5 elements -->

  <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

  <!--  <link href="/static/css/bootstrap.min.css" rel="stylesheet">-->
  <!--  <link href="/static/css/simplebootadmin.css" rel="stylesheet">-->
  <!--  <link href="/static/css/font-awesome.min.css?page=index" rel="stylesheet" type="text/css">-->
  <link rel="stylesheet" href="/static/css/simplebootadminindex.min.css">

  <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
  <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
  <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
  <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <style>
    /*-----------------导航hack--------------------*/
    .nav-list > li.open {
      position: relative;
    }

    .navbar-default {
      background-color: #2C3E50;
      border-color: transparent;
      border-radius: 0;
    }

    .navbar-default .navbar-brand:hover, .navbar-default .navbar-brand {
      color: #ffffff;
    }

    .nav-list > li.open .back {
      display: none;
    }

    .nav-list > li.open .normal {
      display: inline-block !important;
    }

    .nav-list > li.open a {
      padding-left: 7px;
    }

    .nav-list > li .submenu > li > a {
      background: #fff;
    }

    .nav-list > li .submenu > li a > [class*="fa-"]:first-child {
      left: 20px;
    }

    .nav-list > li ul.submenu ul.submenu > li a > [class*="fa-"]:first-child {
      left: 30px;
    }

    #sidebar-shortcuts a {
      padding: 4px 6px;
      line-height: 14px;
    }

    /*----------------导航hack--------------------*/
  </style>

</head>

<body style="min-width: 900px; overflow: hidden;">

<div class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="/admin/index/index" class="navbar-brand" style="min-width: 200px;text-align: center;">PhalconCMS</a>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav navbar-right simplewind-nav">
        <li class="light-blue dropdown" style="border-left:none;">
          <a data-toggle="dropdown" href="" class="dropdown-toggle">
            <span class="glyphicon glyphicon-user"></span>
            <span class="user-info">
								<?php echo $admin['nickname'] ?>
            </span>
            <i class="fa fa-caret-down"></i>
          </a>
          <ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-closer">
            <li>
              <a href=""><span class="glyphicon glyphicon-info-sign"></span> 个人信息</a>
            </li>
            <li><a href="/admin/admin/logout"><span class="glyphicon glyphicon-log-out"></span></i> 退出</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="main-container container-fluid">

  <div class="sidebar" id="sidebar">
    <div class="sidebar-shortcuts" id="sidebar-shortcuts">
      <a class="btn btn-sm btn-danger" href="/admin/dashboard/index" title="" target="iframe"
         data-toggle="tooltip" data-original-title="仪表盘">
        <span class="glyphicon glyphicon-dashboard"></span>
      </a>

      <a class="btn btn-sm btn-success" href="javacript:void(0);" target="iframe"
         data-toggle="tooltip" data-original-title="">
        <span class="glyphicon glyphicon-cog"></span>
      </a>

      <a class="btn btn-sm btn-warning" href="javacript:void(0);" target="iframe"
         data-toggle="tooltip" data-original-title="">
        <span class="glyphicon glyphicon-th-large"></span>
      </a>

      <a class="btn btn-sm btn-info" id="refresh-wrapper" href="javacript:void(0);" data-toggle="tooltip"
         data-original-title="刷新">
        <span class="glyphicon glyphicon-repeat"></span>
      </a>

    </div>
    <div id="nav-wrapper">

      <ul class="nav nav-list">


		  <?php foreach ($menuList as $menu) { ?>
            <li>
              <a target="iframe"
                 href="/admin/<?php echo $menu['controller'] . '/' . $menu['action'] ?>" <?php if (!empty($menu['child']))
			  {
				  echo 'class="dropdown-toggle"';
			  } ?>>
                <span class="<?php echo $menu['icon'] ?>" aria-hidden="false"></span>
                <span class="menu-text normal"> <?php echo $menu['name']; ?> </span>
              </a>
              <ul class="submenu">
				  <?php if (!empty($menu['child']))
				  {
					  $menuChild = $menu['child'];
					  foreach ($menuChild as $child)
					  {
						  if ($child['isShow'])
						  { ?>
                            <li>
                              <a target="iframe"
                                 href="/admin/<?php echo $child['controller'] . '/' . $child['action'] ?>">
                                <span class="<?php echo $child['icon'] ?>" aria-hidden="false"></span>
                                <span class="menu-text"><?php echo $child['name']; ?></span>
                              </a>
                            </li>
						  <?php }
					  }
				  } ?>
              </ul>
            </li>
		  <?php } ?>

      </ul>
    </div>

  </div>

  <div class="main-content">
    <div class="page-content" id="content">
      <iframe src="/admin/dashboard/index" style="width:100%;height: 100%;" frameborder="0" name="iframe" id="iframe1"
              class="appiframe"></iframe>
    </div>
  </div>
</div>

<script src="/static/js/adminindex.js"></script>
<script>
  $(function () {
    $("[data-toggle='tooltip']").tooltip();
    $("li.dropdown").hover(function () {
      $(this).addClass("open");
    }, function () {
      $(this).removeClass("open");
    });
  });

  var ismenumin = $("#sidebar").hasClass("menu-min");
  $(".nav-list").on("click", function (event) {
    var closest_a = $(event.target).closest("a");
    if (!closest_a || closest_a.length == 0) {
      return
    }
    if (!closest_a.hasClass("dropdown-toggle")) {
      if (ismenumin && "click" == "tap" && closest_a.get(0).parentNode.parentNode == this) {
        var closest_a_menu_text = closest_a.find(".menu-text").get(0);
        if (event.target != closest_a_menu_text && !$.contains(closest_a_menu_text, event.target)) {
          return false
        }
      }
      return
    }
    var closest_a_next = closest_a.next().get(0);
    if (!$(closest_a_next).is(":visible")) {
      var closest_ul = $(closest_a_next.parentNode).closest("ul");
      if (ismenumin && closest_ul.hasClass("nav-list")) {
        return
      }
      closest_ul.find("> .open > .submenu").each(function () {
        if (this != closest_a_next && !$(this.parentNode).hasClass("active")) {
          $(this).slideUp(150).parent().removeClass("open")
        }
      });
    }
    if (ismenumin && $(closest_a_next.parentNode.parentNode).hasClass("nav-list")) {
      return false;
    }
    $(closest_a_next).slideToggle(150).parent().toggleClass("open");
    return false;
  });

</script>
</body>
</html>