<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>PhalconCMF</title>
  <meta http-equiv="X-UA-Compatible" content="chrome=1,IE=edge"/>
  <meta name="renderer" content="webkit|ie-comp|ie-stand">
  <meta name="robots" content="noindex,nofollow">
  <!-- HTML5 shim for IE8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <![endif]-->
  <style>
    body {
      background: #fff;
    }

    .wrap {
      margin-top: 180px;
    }
  </style>
  <!--[if lt IE 9]>
  <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>

  <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
  <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
  <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
  <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" crossorigin="anonymous"></script>

  <![endif]-->
  <script>
    if (window.parent !== window.self) {
      document.write              = '';
      window.parent.location.href = window.self.location.href;
      setTimeout(function () {
        document.body.innerHTML = '';
      }, 0);
    }
  </script>
</head>
<body>
<div class="wrap">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <h1 class="text-center">PhalconCMF</h1>
        <form class="js-ajax-form" action="/admin/admin/dologin" method="post">
          <div class="form-group">
            <input type="text" id="input_username" class="form-control" name="username"
                   placeholder="请输入用户名"
                   value="" data-rule-required="true" data-msg-required="">
          </div>

          <div class="form-group">
            <input type="password" id="input_password" class="form-control" name="password"
                   placeholder="请输入密码" data-rule-required="true"
                   data-msg-required="">
          </div>

          <div class="form-group">
            <button class="btn btn-primary btn-block js-ajax-submit" type="submit" style="margin-left: 0px">
              登录
            </button>
          </div>

        </form>
      </div>
    </div>

  </div>
</div>
</body>
</html>
