<ul class="nav nav-tabs">
  <li role="presentation"><a href="/admin/role/list">角色列表</a></li>
  <?php if(empty($roleInfo)){ ?>
    <li role="presentation" class="active"><a href="#">添加角色</a></li>
  <?php }else{ ?>
    <li role="presentation" class="active"><a href="#">角色编辑</a></li>
  <?php } ?>
</ul>


<form class="form-horizontal" method="post">
  <input type="hidden" name="adminRoleId"
         value="<?php echo isset($roleInfo->adminRoleId) ? $roleInfo->adminRoleId : ''; ?>">
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">名称：</label>
    <div class="col-sm-4">
      <input type="text" name="roleName" value="<?php echo isset($roleInfo->roleName) ? $roleInfo->roleName : ''; ?>"
             class="form-control" id="inputEmail3">
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">描述：</label>
    <div class="col-sm-4">
      <textarea class="form-control" name="description"
                rows="6"><?php echo isset($roleInfo->description) ? $roleInfo->description : ''; ?></textarea>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">提交</button>
    </div>
  </div>
</form>