<ul class="nav nav-tabs">
  <li role="presentation"><a href="/admin/role/list">角色列表</a></li>
  <li role="presentation"><a href="/admin/role/edit">添加角色</a></li>
  <li role="presentation" class="active"><a href="#">角色授权</a></li>
</ul>

<div class="panel panel-default" style="margin-top: 20px;">
  <div class="panel-body">
    <form method="post">
	    <?php echo $checkboxHtml; ?>
      <button type="submit" class="btn btn-primary">提交</button>
    </form>
  </div>
</div>

<script>
  
</script>