<div class="wrap js-check-wrap">
  <ul class="nav nav-tabs">
    <li class="active"><a href="/admin/role/list">角色管理</a></li>
    <li><a href="/admin/role/edit">添加角色</a></li>
  </ul>
  <form action="{:url('Rbac/listorders')}" method="post" class="margin-top-20">
    <table class="table table-hover table-bordered">
      <thead>
      <tr>
        <th width="40">ID</th>
        <th align="left">角色名称</th>
        <th align="left">描述</th>
        <th width="160">操作</th>
      </tr>
      </thead>
      <tbody>
	  <?php foreach ($roleList as $role) { ?>
        <tr>
          <td><?php echo $role['adminRoleId']; ?></td>
          <td><?php echo $role['roleName'] ?></td>
          <td><?php echo $role['description'] ?></td>

          <td>
			  <?php if ($role['adminRoleId'] == 1) { ?>
                <font color="#cccccc">权限设置</font>
                <font color="#cccccc">编辑</font>
                <font color="#cccccc">删除</font>
			  <?php } else { ?>
                <a href="/admin/role/auth?id=<?php echo $role['adminRoleId']; ?>">权限设置</a>
                <!-- <a href="javascript:openIframeDialog('{:url('rbac/member',array('id'=>$vo['id']))}','成员管理');">成员管理</a>| -->
                <a href="/admin/role/edit?id=<?php echo $role['adminRoleId']; ?>">编辑</a>
                <a class="js-ajax-delete" href="javascript:if(confirm('确定要删除吗？'))location='/admin/role/delete?id=<?php echo $role['adminRoleId']; ?>'">删除</a>
			  <?php } ?>
          </td>
        </tr>
	  <?php } ?>
      </tbody>
    </table>
  </form>
</div>
