<ul class="nav nav-tabs">
  <li role="presentation"><a href="/admin/adminuser/list">账号列表</a></li>
  <li role="presentation"><a href="/admin/adminuser/edit">添加账号</a></li>
  <li role="presentation" class="active"><a href="/admin/adminuser/list">设置角色</a></li>
</ul>

<form class="form-horizontal" method="post">
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">用户ID：</label>
    <div class="col-sm-4">
      <input type="text" name="adminUserId" value="<?php echo $adminUser['adminUserId'] ?>"
             class="form-control" id="inputEmail3" readonly>
    </div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">用户名：</label>
    <div class="col-sm-4">
      <input type="text" value="<?php echo $adminUser['username'] ?>"
             class="form-control" id="inputEmail3" readonly>
    </div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">昵称：</label>
    <div class="col-sm-4">
      <input type="text" value="<?php echo $adminUser['nickname'] ?>"
             class="form-control" id="inputEmail3" readonly>
    </div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">角色：</label>
    <div class="col-sm-4">
		<?php foreach ($roleList as $role) { ?>
          <div class="checkbox">
            <label>
              <input type="checkbox" name="role[]" value="<?php echo $role['adminRoleId']; ?>" <?php if(in_array($role['adminRoleId'], $checked)){echo 'checked';} ?>>
              <?php echo $role['roleName'] ?>
            </label>
          </div>
		<?php } ?>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">提交</button>
    </div>
  </div>
</form>