<ul class="nav nav-tabs">
	<li><a href="/admin/category/list">分类管理</a></li>
	<li class="active"><a href="/admin/category/edit">添加分类</a></li>
</ul>

<form class="form-horizontal" method="post">
	<input type="hidden" name="settingGroupId" value="">

	<div class="form-group">
		<label for="inputEmail3" class="col-sm-2 control-label">父分类：</label>
		<div class="col-sm-4">
			<input type="text" name="name" value="" class="form-control" id="inputEmail3">
		</div>
	</div>

	<div class="form-group">
		<label for="inputEmail3" class="col-sm-2 control-label">标题：</label>
		<div class="col-sm-4">
			<input type="text" name="name" value="" class="form-control" id="inputEmail3">
		</div>
	</div>

	<div class="form-group">
		<label for="inputEmail3" class="col-sm-2 control-label">别名：</label>
		<div class="col-sm-4">
			<input type="text" name="name" value="" class="form-control" id="inputEmail3">
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-primary">提交</button>
		</div>
	</div>
</form>

