<div class="wrap js-check-wrap">
  <ul class="nav nav-tabs">
    <li class="active"><a href="/admin/category/list">分类管理</a></li>
    <li><a href="/admin/category/edit">添加分类</a></li>
  </ul>
  <form method="post">
    <table class="table table-hover table-bordered">
      <thead>
      <tr>
        <th width="40">ID</th>
        <th align="left">菜单名称</th>
        <th align="left">控制器</th>
        <th align="left">方法</th>
        <th align="left">是否显示</th>
        <th align="left">描述</th>
        <th width="140">操作</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      </tbody>
    </table>
  </form>
</div>