<ul class="nav nav-tabs">
  <li role="presentation"><a href="/admin/menu/list">菜单列表</a></li>
	<?php if (empty($menuInfo)) { ?>
      <li role="presentation" class="active"><a href="#">添加菜单</a></li>
	<?php } else { ?>
      <li role="presentation" class="active"><a href="#">编辑菜单</a></li>
	<?php } ?>
</ul>


<form class="form-horizontal" method="post">
  <input type="hidden" name="menuId"
         value="<?php echo $menuInfo ? $menuInfo->menuId : ''; ?>">

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">上级菜单：</label>
    <div class="col-sm-2"><?php echo $menuSelect; ?></div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">菜单名称：</label>
    <div class="col-sm-4">
      <input type="text" name="name" value="<?php echo $menuInfo ? $menuInfo->name : ''; ?>"
             class="form-control" id="inputEmail3">
    </div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">控制器：</label>
    <div class="col-sm-4">
      <input type="text" name="controller" value="<?php echo $menuInfo ? $menuInfo->controller : ''; ?>"
             class="form-control" id="inputEmail3">
    </div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">方法：</label>
    <div class="col-sm-4">
      <input type="text" name="action" value="<?php echo $menuInfo ? $menuInfo->action : ''; ?>"
             class="form-control" id="inputEmail3">
    </div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">图标：</label>
    <div class="col-sm-4">
      <input type="text" name="icon" value="<?php echo $menuInfo ? $menuInfo->icon : ''; ?>"
             class="form-control" id="inputEmail3">
    </div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">是否显示：</label>
    <div class="col-sm-4">
      <label class="radio-inline">
        <input type="radio" name="isShow" id="inlineRadio1" <?php if ($menuInfo && $menuInfo->isShow)
		{
			echo 'checked';
		} ?> value="1"> 作为菜单显示
      </label>
      <label class="radio-inline">
        <input type="radio" name="isShow" id="inlineRadio2" <?php if ($menuInfo && !$menuInfo->isShow)
		{
			echo 'checked';
		} ?> value="0"> 只作为权限验证
      </label>
    </div>
  </div>

  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">描述：</label>
    <div class="col-sm-4">
      <textarea class="form-control" name="description"
                rows="6"><?php echo $menuInfo ? $menuInfo->description : ''; ?></textarea>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">提交</button>
    </div>
  </div>
</form>

<script>
  function menuSelected(obj) {
    var pid = $(obj).find('option:selected').val();

    if (pid != 0) {
      $.ajax({
        type: 'POST',
        url: '/admin/menu/getChildSelect',
        data: 'pid=' + pid + '&menuId=<?php echo !empty($menuInfo) ? $menuInfo->menuId : 0; ?>',
        dataType: 'JSON',
        success: function (data) {
          if (data.status == 1) {
            $(obj).parent().nextAll().remove();
            $(obj).parent().after('<div class="col-sm-2">' + data.html + '</div>');
          }
        }
      });
    } else {
      $(obj).parent().nextAll().remove();
    }

  }
</script>